# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    container:
      image: castle6610/andestoolschain:1.0.0
        
    steps:
    - uses: actions/checkout@v2
    
    - name: Just Test
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        chmod 775 ./build.sh
        ./build.sh build
        mkdir main_output
        cp -r ./BT_Audio_APP/make/output/* ./main_output/
        
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: release_bin
        path: main_output
        retention-days: 1
      
